server:
  prot:

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    data-username: admin
    data-password: 123456

mybatis:
  type-aliases-package:
    mapper-locations:
      - mapper/*