server:
  prot: 8080

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useUnicode=true&amp&characterEncoding=UTF-8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.course.bean
  mapper-locations:
    - mapper/*